# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-12 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200406_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='markdown 语法'),
        ),
    ]
